name: Pre Merge Checks

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        # Mac OS and Windows are turned off: https://github.com/Citi/gradle-helm-plugin/issues/5
        os: [ ubuntu-latest ]
        jdk: [ 8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
        with:
          gradle-home-cache-cleanup: true
          arguments: build --stacktrace --info
