name: Plugin publish

# This workflow is strictly manual
# https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Branch Check
        if: github.ref != 'refs/heads/master'
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('This workflow must run on master branch only')

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Checkout Repo
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          # Secrets are uploaded via https://docs.github.com/en/actions/security-guides/encrypted-secrets
          # Correct them on https://github.com/Citi/gradle-helm-plugin/settings/secrets/actions
          arguments: publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} --stacktrace
