name: Build and Deploy Website

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    if: github.repository == 'citi/gradle-helm-plugin'
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Checkout Repo
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # Kotlin documentation is only built, but not published yet
          arguments: asciidoctor dokkaHtml

      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy User documentation GitHub Pages (only on master)
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          folder: build/docs/asciidoc/
          # let's publish master branch only for now,
          # however in future it would be better to publish version-based documentation too
          target-folder: latest/userguide/